#!/bin/sh
if [[ $# -lt 1 ]] || [[ $1 == "-h" ]] || [[ $1 == "--help" ]]
then
    echo 'usage$ qfullgen2 {number of nodes}'
    echo 'ex) qfullgen2 1'
    echo 'ex) qfullgen2 -n|--node n027-n028'
    echo 'ex) qfullgen2 -n|--node "n027 n029"'
    exit 1
fi

if [ $1 -eq $1 2>/dev/null ];then
    num=$1
    shift
    node=""
fi

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -n|--node)
    node="$2"
    shift
    shift
    ;;
    *)
    echo "Warning) there are inappropriate options."
    shift
    ;;
esac
done

if [[ $node == "" ]];then
    sed -i -e '/#PBS -q/c\#PBS -q fullgen2' -e "/nodes/c\#PBS -l nodes=${num}:ppn=40:fullgen2" run.sh
#INCAR Change
    if [[ $(grep KPAR INCAR) = "" ]]
    then
    echo "KPAR=" >> INCAR
    fi
    if [[ $(grep NCORE INCAR) = "" ]]
    then
    echo "NCORE=" >> INCAR
    fi
    if [[ $(grep NPAR INCAR) = "" ]]
    then
    echo "NPAR=" >> INCAR
    fi

    sed -i -e "s/KPAR.*/KPAR=$num/g" -e "s/NCORE.*/NCORE=10/g" -e "s/NPAR.*/NPAR=4/g" INCAR
    echo "set nodes=${num}:ppn=40:full"
    echo "set KPAR=$num:NCORE=10:NPAR=4"
else
    echo "You should check appropriate nodes to corresponding with queue."
    if [[ $node =~ - ]];then
        initial=`echo $node|cut -d'-' -f1|cut -d'n' -f2`
        final=`echo $node|cut -d'-' -f2|cut -d'n' -f2`
        nodes=`awk -v i=$initial -v f=$final '
               BEGIN{
                  for(n=i;n<f;n++){
                     printf("n%03d:ppn=40:fullgen2+",n)
                  }
                  printf("n%03d:ppn=40:fullgen2",f)
               }'`
        echo "set nodes=$nodes"
    else
        nodes=""
        for x in $node
        do
            if [[ $nodes == "" ]];then
                nodes=`printf "%s" "${x}:ppn=40:fullgen2"`
            else
                nodes=`printf "%s%s" "$nodes" "+${x}:ppn=40:fullgen2"`
            fi
        done
        echo "set nodes=$nodes"
    fi
    sed -i -e '/#PBS -q/c\#PBS -q fullgen2' -e "/nodes/c\#PBS -l nodes=${nodes}" run.sh
fi

exit 0


exit 0
