#! /bin/sh

function Check_relax {
Folders=($(find . -maxdepth 1 -type d))
E_Last=$(grep "TOTEN" ${Folders[-1]}/OUTCAR -s -R -n | tail -1 | cut -d"=" -f2 | cut -d"e" -f1)
for d in ${Folders[@]}
do
if [[ -a $d/relax.out ]]
then
        Dir_Name2=$(echo $d | rev | cut -d"/" -f1 | rev)
        Dir_Name1=$(echo $d | rev | cut -d"/" -f2 | rev)
        D=${Dir_Name1}/${Dir_Name2}
	M=$(grep "mag=" $d/relax.out -s -R -n | tail -1 | cut -d"=" -f5 )
	E=$(grep "TOTEN" $d/OUTCAR -s -R -n | tail -1 | cut -d"=" -f2 | cut -d"e" -f1)
	T=$(grep LOOP: $d/OUTCAR | awk 'BEGIN{time=0}{time+=$7}END{print time/NR}')

	if [[ $(grep "reached required accuracy - stopping structural energy minimisation" $d/relax.out) ]]
	then
		echo "$D : Relaxed!   $E $E_Last Time: $T Mag= $M"
	elif [[ $(grep "ERROR" $d/relax.out) ]]||[[ $(grep "error" $d/relax.out) ]]
	then
		echo "$D : Un-relaxed $E $E_Last Time: $T Mag= $M"
	else
		echo "$D : Proceeding $E $E_Last Time: $T Mag= $M"
	fi
fi

done
}


#==============================================================================================================================
echo "*--------------------------------------------------------------------------------*"
echo "|                                <Bulk Analyzer>                                 |"
echo "| o Step 1 ENCUT Convergence plot                                                |"
echo "| o Step 2 KPOINTS Convergence plot                                              |"
echo "*--------------------------------------------------------------------------------*"
read -p "몇번째 Step 을 진행할 지 정수로 적어주세요: " STEP
#==============================================================================================================================

if [[ $STEP == 1 ]]
then
Check_relax | cut -d"/" -f2 > E_Conv.dat
fi

